#!/bin/sh
# Compiles the web UI's files into the host tool: embed.sh DIR > web_assets.cpp
set -eu
dir=$1
echo '// Generated by host/embed.sh from the web UI; do not edit.'
echo '#include "web.h"'
echo
n=0
for file in "$dir"/*; do
    [ -f "$file" ] || continue
    echo "static const unsigned char file$n[] = {"
    od -An -v -tx1 "$file" | awk '{ line = ""; for (i = 1; i <= NF; i++) line = line "0x" $i ","; print line }'
    echo "0};"
    n=$((n + 1))
done
echo
echo 'const EmbeddedFile kWebFiles[] = {'
n=0
for file in "$dir"/*; do
    [ -f "$file" ] || continue
    size=$(wc -c < "$file")
    echo "    {\"/$(basename "$file")\", file$n, $((size))},"
    n=$((n + 1))
done
echo '};'
echo "const size_t kWebFileCount = $n;"
